# Generated by Django 3.2.5 on 2021-07-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('label', models.CharField(choices=[('Backlog', 'Backlog'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=15)),
                ('body', models.TextField(max_length=100)),
            ],
        ),
    ]
