# Generated by Django 3.2.5 on 2021-07-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.CharField(choices=[('Backlog', 'Backlog'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=40),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
