# Generated by Django 4.0.1 on 2022-01-22 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210727_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id']},
        ),
    ]
